
export const courses = [
    { id: 1, name: "Chandigarh University Online", totalCourses: 16, image: "/ChandigarhUniversity.webp" },
    { id: 2, name: "Jain University", totalCourses: 15, image: "/JainUniversity.webp" },
    { id: 3, name: "Amity University Online", totalCourses: 19, image: "/AmityUniversity.webp" },
    { id: 4, name: "Sharda University", totalCourses: 17, image: "/ShardaUniversity.webp" },
    { id: 5, name: "Manipal University Jaipur", totalCourses: 19, image: "/ManipalUniversity.webp" },
    { id: 6, name: "Uttaranchal University", totalCourses: 19, image: "/UttaranchalUniversity.jpg" },
    { id: 7, name: "Kurukshetra University", totalCourses: 18, image: "/KurukshetraUniversity.webp" },
    { id: 8, name: "Lovely Professional University", totalCourses: 23, image: "/LPUniversity.webp" },
    { id: 9, name: "UPES Online", totalCourses: 15, image: "/UPESUniversity.webp" },
    { id: 10, name: "DY Patil University", totalCourses: 19, image: "/DYPatilUniversity.webp" },
    { id: 11, name: "Vivekanand Global University", totalCourses: 24, image: "/VivekanandUniversity.webp" },
    { id: 12, name: "GLA University Online", totalCourses: 20, image: "/GLAUniversity.webp" },
    { id: 13, name: "Sikkim Manipal University", totalCourses: 19, image: "/SikkimUniversity.jpg" },
    { id: 14, name: "Vignan University Online", totalCourses: 24, image: "/VignanUniversity.webp" },
    { id: 15, name: "Amrita Ahead Online", totalCourses: 15, image: "/AmrityUniversity.jpg" },
    { id: 16, name: "Shoolini University Online", totalCourses: 22, image: "/ShooliniUniversity.webp" },
    { id: 17, name: "NMIMS University", totalCourses: 23, image: "/NMIMSUniversity.webp" },
    { id: 18, name: "Andra University", totalCourses: 23, image: "/AndraUniversity.jpg" },
    { id: 19, name: "MAHE University", totalCourses: 22, image: "/MAHEUniversity.jpg" },
    { id: 20, name: "Aligarh Muslim University", totalCourses: 15, image: "/AligarhUniversity.jpg" },
    { id: 21, name: "Jamia Hamdard University", totalCourses: 15, image: "/JamiaUniversity.jpg" },
    { id: 22, name: "Mizoram University", totalCourses: 21, image: "/MizoramUniversity.jpg" },
    { id: 23, name: "Mangalayatan University", totalCourses: 19, image: "/MangalayatanUniversity.jpg" },

  ];

 export const universities = [
    {
      id: 1,
      name: "Chandigarh University Online",
      approvals: "NAAC A+ | UGC Entitled | WES | ACU | AICTE",
      educationMode: "Online Programmes",
      ranking: "NIRF Rank: 14",
      examinationMode: "On Demand Computer Based Examination",
      highestPlacement: "1200000",
      averagePlacement: "900000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/CUlogo.png",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 2,
      name: "Jain University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Jainlogo.jpg",
      EMIOptions: "Not Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 3,
      name: "Amity University Online",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Amitylogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 4,
      name: "Sharda University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Shardalogo.jpg",
      EMIOptions: "Not Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 5,
      name: "Manipal University Jaipur",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Manipallogo.jpg",
      EMIOptions: "Not Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 6,
      name: "Uttaranchal University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Uttaranchallogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 7,
      name: "Kurukshetra University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/KUlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 8,
      name: "Lovely Professional University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/LPUlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 9,
      name: "UPES Online",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/UPESlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 10,
      name: "DY Patil University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/DYPatillogo.jpg",
      EMIOptions: "Not Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 11,
      name: "Vivekanand Global University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/VGUlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
      {
      id: 12,
      name: "GLA University Online",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/GLAlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
     {
      id: 13,
      name: "Sikkim Manipal University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/SMUlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 14,
      name: "Vignan University Online",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Vignanlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 15,
      name: "Amrita Ahead Online",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Amritalogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 16,
      name: "Shoolini University Online",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/Shoolinilogo.png",
      EMIOptions: "Not Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 17,
      name: "NMIMS University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/NMIMSlogo.png",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 18,
      name: "Andra University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/AndraLogo.jpg",
      EMIOptions: "Not Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 19,
      name: "MAHE University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/MAHElogo.png",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 20,
      name: "Aligarh Muslim University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/AMUlogo.jpg",
      EMIOptions: "Not Available",
      placements:["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 21,
      name: "Jamia Hamdard University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/JHUlogo.jpg",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 22,
      name: "Mizoram University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/MizoramLogo.jpg",
      EMIOptions: "Not Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
    {
      id: 23,
      name: "Mangalayatan University",
      approvals: "NAAC A+ | UGC | AICTE | AIU | WES",
      educationMode: "Online Programmes",
      ranking: "5th Multidisciplinary Emerging University, 2023",
      examinationMode: "Online",
      highestPlacement: "5200000",
      averagePlacement: "1000000",
      courses: "MBA, MCom, MCA, MA, BCA, BA, BBA, BCom",
      image: "/MangalayatanLogo.png",
      EMIOptions: "Available",
      placements: ["/kpmg.webp", "/dell.webp", "/Sony.webp","/siemens.webp","/amazon.webp","/Nielsen.webp","/royal-enfield.webp"],
    },
  ];
